[2022-07-07 16:27:30,908] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: last30days_covid.extract manual__2022-07-07T09:27:29.509264+00:00 [queued]>
[2022-07-07 16:27:30,925] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: last30days_covid.extract manual__2022-07-07T09:27:29.509264+00:00 [queued]>
[2022-07-07 16:27:30,926] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-07 16:27:30,926] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-07 16:27:30,926] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-07 16:27:30,955] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): extract> on 2022-07-07 09:27:29.509264+00:00
[2022-07-07 16:27:30,959] {standard_task_runner.py:52} INFO - Started process 2799 to run task
[2022-07-07 16:27:30,964] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'last30days_covid', 'extract', 'manual__2022-07-07T09:27:29.509264+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/last30days_covid.py', '--cfg-path', '/tmp/tmp7oc8_0b8', '--error-file', '/tmp/tmpm295gayp']
[2022-07-07 16:27:30,965] {standard_task_runner.py:80} INFO - Job 10: Subtask extract
[2022-07-07 16:27:31,096] {task_command.py:370} INFO - Running <TaskInstance: last30days_covid.extract manual__2022-07-07T09:27:29.509264+00:00 [running]> on host DESKTOP-FMPNIM0.localdomain
[2022-07-07 16:27:31,240] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=last30days_covid
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-07-07T09:27:29.509264+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-07T09:27:29.509264+00:00
[2022-07-07 16:27:31,241] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-07 16:27:31,241] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/home/luan/projects/covid_dashboard/pipelines/vn_etl/bash_scripts/last30days_etl/1_extract.sh ']
[2022-07-07 16:27:31,248] {subprocess.py:85} INFO - Output:
[2022-07-07 16:27:31,257] {subprocess.py:92} INFO - /home/luan/projects/covid_dashboard/pipelines/vn_etl/bash_scripts/last30days_etl/1_extract.sh: line 5: scrapy: command not found
[2022-07-07 16:27:31,257] {subprocess.py:96} INFO - Command exited with return code 127
[2022-07-07 16:27:31,287] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-07 16:27:31,292] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=last30days_covid, task_id=extract, execution_date=20220707T092729, start_date=20220707T092730, end_date=20220707T092731
[2022-07-07 16:27:31,313] {standard_task_runner.py:92} ERROR - Failed to execute job 10 for task extract (Bash command failed. The command returned a non-zero exit code 127.; 2799)
[2022-07-07 16:27:31,341] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-07 16:27:31,431] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
