[2022-07-07 16:22:26,154] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: incre_global_covid.is_api_available manual__2022-07-07T09:22:24.661844+00:00 [queued]>
[2022-07-07 16:22:26,176] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: incre_global_covid.is_api_available manual__2022-07-07T09:22:24.661844+00:00 [queued]>
[2022-07-07 16:22:26,176] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-07 16:22:26,177] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-07 16:22:26,177] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-07 16:22:26,219] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-07 09:22:24.661844+00:00
[2022-07-07 16:22:26,222] {standard_task_runner.py:52} INFO - Started process 12871 to run task
[2022-07-07 16:22:26,227] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'incre_global_covid', 'is_api_available', 'manual__2022-07-07T09:22:24.661844+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/incre_global_covid.py', '--cfg-path', '/tmp/tmp7qrbh5sp', '--error-file', '/tmp/tmp8loalk8w']
[2022-07-07 16:22:26,229] {standard_task_runner.py:80} INFO - Job 6: Subtask is_api_available
[2022-07-07 16:22:26,349] {task_command.py:370} INFO - Running <TaskInstance: incre_global_covid.is_api_available manual__2022-07-07T09:22:24.661844+00:00 [running]> on host DESKTOP-FMPNIM0.localdomain
[2022-07-07 16:22:26,508] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=incre_global_covid
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-07T09:22:24.661844+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-07T09:22:24.661844+00:00
[2022-07-07 16:22:26,509] {http.py:97} INFO - Poking: covid-19/countries?yesterday=yesterday
[2022-07-07 16:22:26,547] {base.py:68} INFO - Using connection ID 'global_covid_api' for task execution.
[2022-07-07 16:22:26,552] {http.py:129} INFO - Sending 'GET' to url: https://disease.sh/v3/covid-19/countries?yesterday=yesterday
[2022-07-07 16:22:28,178] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-07 16:22:28,228] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=incre_global_covid, task_id=is_api_available, execution_date=20220707T092224, start_date=20220707T092226, end_date=20220707T092228
[2022-07-07 16:22:28,301] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-07 16:22:28,468] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
