[2022-07-07 16:22:29,418] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: incre_global_covid.update_date_table manual__2022-07-07T09:22:24.661844+00:00 [queued]>
[2022-07-07 16:22:29,457] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: incre_global_covid.update_date_table manual__2022-07-07T09:22:24.661844+00:00 [queued]>
[2022-07-07 16:22:29,457] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-07 16:22:29,458] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-07 16:22:29,458] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-07 16:22:29,487] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): update_date_table> on 2022-07-07 09:22:24.661844+00:00
[2022-07-07 16:22:29,491] {standard_task_runner.py:52} INFO - Started process 13073 to run task
[2022-07-07 16:22:29,497] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'incre_global_covid', 'update_date_table', 'manual__2022-07-07T09:22:24.661844+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/incre_global_covid.py', '--cfg-path', '/tmp/tmppn4l69dg', '--error-file', '/tmp/tmpetllwprp']
[2022-07-07 16:22:29,499] {standard_task_runner.py:80} INFO - Job 7: Subtask update_date_table
[2022-07-07 16:22:29,693] {task_command.py:370} INFO - Running <TaskInstance: incre_global_covid.update_date_table manual__2022-07-07T09:22:24.661844+00:00 [running]> on host DESKTOP-FMPNIM0.localdomain
[2022-07-07 16:22:29,978] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=incre_global_covid
AIRFLOW_CTX_TASK_ID=update_date_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-07T09:22:24.661844+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-07T09:22:24.661844+00:00
[2022-07-07 16:22:29,979] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-07 16:22:29,981] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/home/luan/projects/covid_dashboard/pipelines/global/incre/update_date_table.sh ']
[2022-07-07 16:22:29,999] {subprocess.py:85} INFO - Output:
[2022-07-07 16:22:30,245] {subprocess.py:92} INFO - /home/luan/projects/covid_dashboard/pipelines/global/incre/update_date_table.sh: line 1: source: /home/luan/projects/covid_dashboard/venv/bin/python: cannot execute binary file
[2022-07-07 16:22:30,443] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-07 16:22:30,488] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=incre_global_covid, task_id=update_date_table, execution_date=20220707T092224, start_date=20220707T092229, end_date=20220707T092230
[2022-07-07 16:22:30,533] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-07 16:22:30,617] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
